// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drndgwcgrhjodnixcfam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybmRnd2Nncmhqb2RuaXhjZmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Mzk5MDgsImV4cCI6MjA2NTAxNTkwOH0.DtFxdkIRewk2uKdYeTsB0xP-ksMTcEfgtQOD7tAp3OQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);